# Generated by Django 4.1.7 on 2024-02-22 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='netid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 31, 10, 991987, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
