# Generated by Django 4.1.7 on 2023-03-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransaction',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subpurchase',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
            preserve_default=False,
        ),
    ]
