# Generated by Django 4.1.7 on 2024-02-18 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 15, 52, 55, 79790, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
