# Generated by Django 4.1.7 on 2023-03-12 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_customer_date_created_customer_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 11, 10, 5, 91332, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
