# Generated by Django 4.1.7 on 2023-05-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_subpurchase_date_created_subpurchase_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransaction',
            name='account_code',
            field=models.IntegerField(default=3002, help_text='account code (grootboekrekeningnummer) for income'),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='vat_code',
            field=models.CharField(default='0', help_text='BTW code of the transaction.', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 56, 27, 792589, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
