# Generated by Django 4.1.7 on 2023-03-29 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_subpurchase_date_created_subpurchase_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 30, 5, 327318, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
