# Generated by Django 4.1.7 on 2023-03-29 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 31, 48, 508467, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
