# Generated by Django 4.1.7 on 2023-05-14 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_subtransaction_vat_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='encrypted_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='encrypted_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 9, 0, 22, 546632, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
