# Generated by Django 4.1.7 on 2023-03-29 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 40, 46, 224010, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
