# Generated by Django 4.1.7 on 2023-04-02 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 12, 4, 6, 485107, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
