# Generated by Django 4.1.7 on 2023-05-14 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_customer_encrypted_code_customer_encrypted_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 9, 28, 35, 111513, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
