# Generated by Django 3.2.8 on 2023-04-22 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 14, 16, 15, 676806, tzinfo=utc), help_text='Date of the transaction.'),
        ),
    ]
