# Generated by Django 4.1.7 on 2023-05-20 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_customer_encrypted_code_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 44, 48, 490743, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
