# Generated by Django 4.1.7 on 2023-05-20 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_customer_sub_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 54, 39, 646063, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
