# Generated by Django 3.2.8 on 2023-04-23 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 16, 48, 9, 486030, tzinfo=utc), help_text='Date of the transaction.'),
        ),
    ]
