# Generated by Django 4.1.7 on 2023-05-20 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_customer_is_active_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 56, 8, 351779, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
