# Generated by Django 3.2.8 on 2023-05-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_subtransaction_vat_code_and_more'),
        ('transactions', '0015_alter_transaction_date'),
    ]

    operations = [
    ]
