# Generated by Django 3.2.8 on 2023-05-04 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_merge_20230504_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 8, 1, 9, 525401, tzinfo=utc), help_text='Date of the transaction.'),
        ),
    ]
