# Generated by Django 4.1.7 on 2023-05-21 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_remove_customer_is_active_remove_customer_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefix',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 22, 13, 378090, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
