# Generated by Django 4.1.7 on 2023-05-21 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sub',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 44, 19, 880382, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
