# Generated by Django 4.1.7 on 2023-05-26 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_customer_sub_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 20, 33, 22, 838455, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
