# Generated by Django 4.1.7 on 2023-05-30 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_transaction_customer_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='encrypted_uuid',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 14, 1, 50, 578783, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
