# Generated by Django 4.1.7 on 2023-05-04 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 12, 6, 50, 55467, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
