# Generated by Django 4.1.7 on 2023-05-04 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 13, 43, 41, 237880, tzinfo=datetime.timezone.utc), help_text='Date of the transaction.'),
        ),
    ]
