# Generated by Django 4.1.7 on 2024-02-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_makrobon_makrobonitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakroBon',
            new_name='MakroInvoice',
        ),
        migrations.RenameModel(
            old_name='MakroBonItem',
            new_name='MakroInvoiceItem',
        ),
        migrations.AlterModelOptions(
            name='makroinvoice',
            options={'ordering': ['-invoice_date'], 'verbose_name_plural': 'Makro Invoices'},
        ),
    ]
