# Generated by Django 4.1.7 on 2023-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_created_product_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account_code',
            field=models.IntegerField(default=8310, help_text='account code (grootboekrekeningnummer)for income'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_code',
            field=models.CharField(default='0', help_text='BTW code of the transaction.', max_length=3),
        ),
    ]
