# Generated by Django 4.1.7 on 2023-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_account_code_product_vat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_code',
        ),
        migrations.AddField(
            model_name='product',
            name='vat_percentage',
            field=models.IntegerField(default=0, help_text='BTW percentage of the transaction.'),
        ),
    ]
