# Generated by Django 4.1.7 on 2024-02-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_vat_code_product_vat_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account_code',
            field=models.IntegerField(default=8310, help_text='account code (grootboekrekeningnummer) for income'),
        ),
    ]
