# Generated by Django 3.2.8 on 2023-05-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_article_number_alter_product_id'),
        ('products', '0008_remove_product_vat_code_product_vat_percentage'),
    ]

    operations = [
    ]
