# Generated by Django 3.2.8 on 2023-05-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20230504_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account_code',
            field=models.IntegerField(default=8310, help_text='account code (grootboekrekeningnummer) for income'),
        ),
    ]
