version: "3.9"
   
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - prod.env
    depends_on:
      - db
  
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tally
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres-data: